sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
  jobs:
    - REPOSITORY: stretch
      DISTRIBUTION: current
      PKGTOOLS_COMMIT: origin/master
      ARCHITECTURE: amd64
    - REPOSITORY: buster
      DISTRIBUTION: current
      ARCHITECTURE: amd64
      PKGTOOLS_COMMIT: origin/master
      UPLOAD: scp
    - REPOSITORY: buster
      DISTRIBUTION: current
      ARCHITECTURE: i386
      PKGTOOLS_COMMIT: origin/master
      UPLOAD: scp

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build
- openssl aes-256-cbc -K $encrypted_760a309a5163_key -iv $encrypted_760a309a5163_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
- docker-compose -f docker-compose.build.yml run pkgtools
- [ "$TRAVIS_BRANCH" != "master" ] || [ "$TRAVIS_PULL_REQUEST" == "true" ] && export UPLOAD=
- docker-compose -f docker-compose.build.yml run build

notifications:
  email: false
  slack:
    rooms:
      secure: "pBnIYpluBBINa6aGlMzevVZyp0VRZqQLvwJkEZQMZnYIM/r4aBk2HZEfS2sS5QYYOQMbfJj61hT3VC3pG5QgWpbwK14wX+rrcI2jhYt71WN95ciaNY38PjLYPh8EGhbvQp0Oz7/WoK5j+TPcuxzC5u/Q6oV8hc0BSEOE8xJ57G10y9b9At1tGiRKSgSQDFJJbmPC3W36u716r9kR6rPsaNhajqJ3QUqy4M82p4ewcVhupYfU8NGIU1D7QE60gyX0yBdSJ3t/L1fDIHIX6jPpetrRsE5/Pg/4OErdDihdWZHML75l3mafsnrKQ8o2Q/nj+OmWOLn+g6rRd5S3EGaZBeU7ou7n3WykMecZwZ9YZQXW3aMQvSkbIhEjXJtWynmISPmpjiZr4DawfB41sVjtsTuz87LUz1ifcDKYnoU46hEiWN9Akk7vm0YMrJdrDCMlj5IHC7q4VBr1X9wKHRH07sz/4eX8FNcNCyo05Kz+lcZ4M3mSQ4B5hI0A1VU/cgCmcVMzOgBVZYACFqF25HVnysL4rvi9u5QyCXtYfUz7Nc93+UMFcNucEhQ3jA7DvcIfMBnD65uvPp4cQNNA785iQNy6xZtDuLeMQGR4s2a8rNnZQcZDN85imx7KVREM0+sHI5P2s5mXjDsHf7J5dL6bWZPscBbs/0dpkBj0Hgja/tQ="
    on_success: change
    on_failure: always
