sudo: required
services:
- docker
before_install:
- docker pull untangleinc/ngfw:build
script:
- docker-compose -f docker-compose.build.yml run build
notifications:
  email: false
  slack:
    rooms:
      secure: ZRNoMZDLaGKCmBUak7xoNYW2Vv9vZq1utH1K+fYrRXXzEA2aQ1w/UUaWWWHmmHcOLSNvdj2IlS3y5WFZbgOfAmMnw+DnEGIRVrNx4jLYlN1i2GF9tMLWVrcnsDnaH5X0gvxRtUCTUNDthvuUbKEZMdxJ89ZF5FBIcd9jC6qmFHuGED3Cg2Z9NUXvzl6Wo254XZIjvKL1P5RtlMBfiTWdPOtQ/wloPvLhMe1bFQjkr6k9WQimWZ3Kt+pKEBtcFKi8kzZu9Bkj68SJ4NYHPOe1BtfT4Kbk6GegkqFjqN0jank7OX/b/NF9RvvHGUnhTHMw2Lu2YxFgrDfWZIPZzjpg1+Zya2Z7ehS2FJoT5da5XNy84P9AS3C5iFx0yDWgouMjvp2fcP+SujCfN9BP8qVC/zbKocxK6thpM2TPKPgp55Cr12GsQGAlkUxTmoaWiZeyHmSfBAwT0tH0iVuO2fuLsXLuM+W8bMAJ90Kk8eB1uYrZ63hxW+dL57Ab/mU5ZvnLJdAFd9YGgFlbzW2pvIHDzQWjHLdaYm9ujE4JuQ3UIJQGcIhGIKwLrOi90qVaXWc5UX9Lq4wOCIY5ifgPlWybzXZi6TGQE0AtYB3Ty58Mndy2fyPhu/pW47xSk9aXDEKYEQUYyvgz+0M1SoUZB5sBmLrysEIYb/Vo0MkG/CLlpd4=
    on_success: change
    on_failure: always
