sudo: required

git:
  depth: false

services:
- docker

env:
  global:
    - SSH_KEY: /tmp/travis-buildbot.rsa
  jobs:
    - REPOSITORY: stretch
      DISTRIBUTION: current
      PKGTOOLS_COMMIT: origin/master
    - REPOSITORY: buster
      DISTRIBUTION: current
      PKGTOOLS_COMMIT: origin/master
      UPLOAD: scp

before_install:
- docker pull untangleinc/ngfw:${REPOSITORY}-build
- openssl aes-256-cbc -K $encrypted_760a309a5163_key -iv $encrypted_760a309a5163_iv -in .travis/buildbot.rsa.enc -out ${SSH_KEY} -d
- chmod 600 ${SSH_KEY}

script:
- docker-compose -f docker-compose.build.yml run pkgtools
- docker-compose -f docker-compose.build.yml run build

notifications:
  email: false
  slack:
    rooms:
      secure: "q1N+nVN1T4Y5PRO3YhnUjx5lztEnUk6tNln3BYX8Rw4YG8mp6OlyHdmstlVf4V/FTZJ1MYyogsq/NfanxP2JT0Gwbh+9xlgJVxIifGmiG38npROGdaWwJlB3S61jjFG8oTlTDJJPBIt6J31yF5vT8xSadir901uH+kNJBxv0zECD4FelZoxmQDr3uoFJEqA1x1VT7yDuxhgDXbMPKVs7o1eTB5tMBeMViMpFtrPQ4f90KHucOiO3xv4TGVl/DyJTdrdJTOEMT7dLwcn54KKXvhC5OC4uQfCDS9XzDax0dadBqGKHbOVPM4ZewOr/lv3uqYYxctF4e41rIxYyp83B0VpUh2W3vz3qslkZ8bzVCbxmdzQ+KJFDDqbAsdfvzpWW8X1DJ0k+yyzO56meMAexfGvT63pf49woFa9y37xI3C0WQDhFE8RChfUZBN1366JhaDBQwrXkqbKIUARFj/jOBMb6KZbREpFPCIAxwnc8RlwwsM54fCEyFqAqjng8t9Sp5/3/6uuL8HVDQ0edY2erzIjO4HghSJ+8q+xmWrCNlOJzuSlfeKcWfJWKL+2RL3TXEO5rcEggixenv4iDSNEyidy1soPz9BkaRUZPFI0Pg4zfgyZNwG/n32A6D/oxcc39tcLo5feiMywZP9IHX3+ph3oQQSlimvdsMqEi6rKUIvY="
    on_success: change
    on_failure: always
