version: '3'
services:
    pkgtools:
      image: untangleinc/pkgtools
      environment:
        - PKGTOOLS_URL=${PKGTOOLS_URL:-https://github.com/untangle/ngfw_pkgtools}
        - PKGTOOLS_COMMIT=${PKGTOOLS_COMMIT:-origin/master}
      volumes:
        - pkgtools:/opt/untangle/ngfw_pkgtools
      entrypoint: >
        bash -c "
        git remote set-url origin $${PKGTOOLS_URL} &&
        git fetch -a &&
        git clean -f -d &&
        git reset --hard &&
        git checkout $${PKGTOOLS_COMMIT}"

    build:
      image: untangleinc/ngfw:${REPOSITORY:-stretch}-build
      environment:
        - REPOSITORY=${REPOSITORY:-stretch}
        - DISTRIBUTION=${DISTRIBUTION:-current}
        - UPLOAD=${UPLOAD} # default to empty: "no upload"
        - VERBOSE=${VERBOSE} # default to empty: "not verbose"
        - PACKAGE=${PACKAGE} # default to empty: "all packages"
      extra_hosts:
        # from the inside, pass package-server's internal IP instead
        - "package-server:${PACKAGE_SERVER_IP:-173.14.28.193}"
      volumes:
        - .:/opt/untangle/build
        - pkgtools:/opt/untangle/ngfw_pkgtools:ro

volumes:
  pkgtools:
